import type { EnvSchema } from "../types/schema.js";

const HEADER = [
  "# Generated by envyra from your env config. Do not edit by hand.",
  "# Run `npx envyra sync` to regenerate.",
];

function formatDefault(value: unknown): string {
  if (typeof value === "string") {
    return value;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  return JSON.stringify(value);
}

/**
 * Render `.env.example` from the schema.
 *
 * The file is fully managed by envyra: the output is deterministic (schema
 * key order, stable formatting), so re-running `sync` without schema changes
 * produces no diff.
 *
 * Security rules:
 * - only schema defaults and `example` values are written, never current
 *   runtime values
 * - variables marked `secret: true` are always written empty
 */
export function renderEnvExample(schema: EnvSchema): string {
  const lines: string[] = [...HEADER, ""];

  for (const [key, spec] of Object.entries(schema)) {
    if (spec.description !== undefined) {
      lines.push(`# ${spec.description}`);
    }
    if (spec.type === "enum") {
      lines.push(`# Allowed values: ${spec.values.map((v) => JSON.stringify(v)).join(", ")}`);
    }
    if (spec.required === false && spec.default === undefined && spec.example === undefined) {
      lines.push("# Optional.");
    }

    const secret = spec.secret === true;
    let value = "";
    if (!secret) {
      if (spec.example !== undefined) {
        value = spec.example;
      } else if (spec.default !== undefined) {
        value = formatDefault(spec.default);
      }
    }
    lines.push(`${key}=${value}`);
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}
